import React from 'react'
import { useLanguage } from '../i18n/LanguageContext'
import { useNavigate } from 'react-router-dom'
import { jsPDF } from 'jspdf'

export default function Dashboard({ user }){
  const { t, language } = useLanguage()
  const navigate = useNavigate()

  const handleEdit = () => {
    navigate('/profile')
  }

  const handleDownloadHandbook = () => {
    const doc = new jsPDF()
    let y = 20
    doc.setFontSize(18)
    doc.text(`${t('dashboardWelcome')} ${user?.name || user?.email}`, 14, y)
    y += 10
    doc.setFontSize(12)
    doc.text(t('dashboardActivity'), 14, y)
    y += 12

    doc.setFontSize(14)
    doc.text(t('learningProgress'), 14, y)
    y += 8
    doc.setFontSize(12)
    doc.text(`${t('learning.courseTitle')} — ${t('learning.progressPercent')}`, 16, y)
    y += 10

    doc.setFontSize(14)
    doc.text(t('savedItems'), 14, y)
    y += 8
    doc.setFontSize(12)
    doc.text(`• ${t('saved.pmKisan')}`, 16, y)
    y += 8
    doc.text(`• ${t('saved.farmerMarket')}`, 16, y)
    y += 8
    doc.text(`• ${t('saved.onlineCourse')}`, 16, y)
    y += 12

    doc.setFontSize(14)
    doc.text(t('activityMonth'), 14, y)
    y += 8
    doc.setFontSize(12)
    doc.text(`💬 ${t('messages')}: 12`, 16, y)
    y += 8
    doc.text(`🎓 ${t('lessons')}: 5`, 16, y)
    y += 8
    doc.text(`💼 ${t('queries')}: 3`, 16, y)
    y += 12

    doc.setFontSize(14)
    doc.text(t('notifications'), 14, y)
    y += 8
    doc.setFontSize(12)
    doc.text(`${t('notification.newSchemeLabel')}: ${t('newScheme')}`, 16, y)
    y += 8
    doc.text(`${t('notification.courseUpdateLabel')}: ${t('courseUpdate')}`, 16, y)
    y += 12

    doc.setFontSize(14)
    doc.text(t('yourInfo'), 14, y)
    y += 8
    doc.setFontSize(12)
    doc.text(`${t('label.email')}: ${user?.email || ''}`, 16, y)
    y += 8
    doc.text(`${t('label.status')}: ${t('verified')}`, 16, y)
    y += 8
    doc.text(`${t('label.language')}: ${t(`lang.${language}`)}`, 16, y)

    // Footer
    doc.setFontSize(10)
    doc.text('Generated by Sahaay', 14, 280)

    doc.save('Sahaay_Handbook.pdf')
  }

  return (
    <div>
      <h1 style={{marginBottom: 8}}>{t('dashboardWelcome')} {user?.name || user?.email}! 👋</h1>
      <p style={{color: '#6b7280', marginBottom: 32}}>{t('dashboardActivity')}</p>

      <div className="dashboard-grid">
        <div className="dashboard-card">
          <h3>📚 {t('learningProgress')}</h3>
          <div style={{marginTop: 12}}>
            <div style={{display: 'flex', justifyContent: 'space-between', marginBottom: 8}}>
              <span>{t('learning.courseTitle')}</span>
              <span style={{color: '#10b981', fontWeight: 600}}>{t('learning.progressPercent')}</span>
            </div>
            <div style={{background: '#e5e7eb', height: 8, borderRadius: 4, overflow: 'hidden'}}>
              <div style={{background: '#10b981', height: '100%', width: '75%'}}></div>
            </div>
          </div>
        </div>

        <div className="dashboard-card">
          <h3>💾 {t('savedItems')}</h3>
          <ul style={{listStyle: 'none', marginTop: 12}}>
            <li style={{marginBottom: 8}}>✓ {t('saved.pmKisan')}</li>
            <li style={{marginBottom: 8}}>✓ {t('saved.farmerMarket')}</li>
            <li>✓ {t('saved.onlineCourse')}</li>
          </ul>
        </div>

        <div className="dashboard-card">
          <h3>📊 {t('activityMonth')}</h3>
          <div style={{marginTop: 12, fontSize: 14, color: '#6b7280'}}>
            <div style={{marginBottom: 8}}>💬 {t('messages')}: 12</div>
            <div style={{marginBottom: 8}}>🎓 {t('lessons')}: 5</div>
            <div>💼 {t('queries')}: 3</div>
          </div>
        </div>

        <div className="dashboard-card">
          <h3>🔔 {t('notifications')}</h3>
          <div style={{marginTop: 12, fontSize: 14}}>
            <div style={{marginBottom: 12, padding: 8, background: '#fef3c7', borderRadius: 6}}>
              <strong>{t('notification.newSchemeLabel')}</strong> {t('newScheme')}
            </div>
            <div style={{padding: 8, background: '#dbeafe', borderRadius: 6}}>
              <strong>{t('notification.courseUpdateLabel')}</strong>: {t('courseUpdate')}
            </div>
          </div>
        </div>

        <div className="dashboard-card">
          <h3>💳 {t('yourInfo')}</h3>
          <div style={{marginTop: 12, fontSize: 14, color: '#6b7280'}}>
            <div style={{marginBottom: 8}}>{t('label.email')}: {user?.email}</div>
            <div style={{marginBottom: 8}}>{t('label.status')}: {t('verified')} ✓</div>
            <div>{t('label.language')}: {t(`lang.${language}`)}</div>
          </div>
        </div>

        <div className="dashboard-card">
          <h3>⚡ {t('quickActions')}</h3>
          <div style={{marginTop: 12, display: 'flex', flexDirection: 'column', gap: 8}}>
            <button onClick={handleEdit} className="btn btn-primary" style={{fontSize: 12}}>{t('editProfile')}</button>
            <button onClick={handleDownloadHandbook} className="btn btn-secondary" style={{fontSize: 12}}>{t('downloadHandbook')}</button>
          </div>
        </div>
      </div>

      <div className="card" style={{marginTop: 32}}>
        <h3>{t('impact')}</h3>
        <div style={{marginTop: 16, display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))', gap: 16}}>
          <div style={{textAlign: 'center', padding: 16, background: '#f0f9ff', borderRadius: 8}}>
            <div style={{fontSize: 28, fontWeight: 700, color: '#0b5cff'}}>8</div>
            <p style={{color: '#6b7280', fontSize: 14}}>{t('schemesFound')}</p>
          </div>
          <div style={{textAlign: 'center', padding: 16, background: '#f0fdf4', borderRadius: 8}}>
            <div style={{fontSize: 28, fontWeight: 700, color: '#10b981'}}>5</div>
            <p style={{color: '#6b7280', fontSize: 14}}>{t('coursesStarted')}</p>
          </div>
          <div style={{textAlign: 'center', padding: 16, background: '#fef3c7', borderRadius: 8}}>
            <div style={{fontSize: 28, fontWeight: 700, color: '#f59e0b'}}>12</div>
            <p style={{color: '#6b7280', fontSize: 14}}>{t('marketConnections')}</p>
          </div>
        </div>
      </div>
    </div>
  )
}
